apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: kubeconfig-volume
          secret:
            secretName: {{ .Values.target.kubeconfig.secret.name }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --enable-leader-election
            - --identifier={{ include "controller.identifier" $ }}
            - --ingress-class={{ .Values.ingressClass.name }}
            - --controller-class={{ include "controller.value" $ }}
            {{- with $.Values.target }}
              {{- with .ingressClass }}
            - --target-ingress-class={{ . }}
              {{- end }}
              {{- with .namespace }}
            - --target-namespace={{ . }}
              {{- end }}
              {{- with .issuer }}
                {{- if .name }}
            - --target-issuer-name={{ .name }}
                {{- end }}
              {{- end }}
            {{- end }}
            - --target-kubeconfig=/target-kubeconfig.yaml
          volumeMounts:
          - name: kubeconfig-volume
            mountPath: /target-kubeconfig.yaml
            subPath: {{ .Values.target.kubeconfig.secret.key }}
          ports:
          - name: metrics
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12}}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
