apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "target-rbac.fullname" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "target-rbac.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "target-rbac.fullname" $ }}
  apiGroup: rbac.authorization.k8s.io