name: Integration Test

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

permissions: read-all

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Check secret
        id: checksecret
        uses: peak-scale/github-actions/exists@38322faabccd75abfa581c435e367d446b6d2c3b # v0.1.0
        with:
          value: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '1.19'
      - name: Run integration tests
        run: |
          make integration-test
      - name: Upload coverage reports to Codecov
        if: steps.checksecret.outputs.result == 'true'
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          files: ./test/integration/cover.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
