name: Integration Test

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

permissions: read-all

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check secret
        id: checksecret
        uses: oliverbaehler/github-actions/exists@979018716f7d0cbe8d2711f572b350afad4ef211 # v0.1.1
        with:
          value: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Run integration tests
        run: |
          make integration-test
      - name: Upload coverage reports to Codecov
        if: steps.checksecret.outputs.result == 'true'
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          files: ./test/integration/cover.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
