name: Integration Test

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

permissions: read-all

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Check secret
        id: checksecret
        uses: peak-scale/github-actions/exists@38322faabccd75abfa581c435e367d446b6d2c3b # v0.1.0
        with:
          value: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.19'
      - name: Run integration tests
        run: |
          make integration-test
      - name: Upload coverage reports to Codecov
        if: steps.checksecret.outputs.result == 'true'
        uses: codecov/codecov-action@4fe8c5f003fae66aa5ebb77cfd3e7bfbbda0b6b0 # v3.1.5
        with:
          files: ./test/integration/cover.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
